### ISSUE TITLE
Sandy Bridge config.plist guide DeviceProperties conflicting information

### ISSUE THREAD

**Issue by donderstock** [dortania/bugtracker#113]
On the config.plist guide page for Sandy Bridge, DeviceProperties section, the proper device-id for PciRoot(0x0)/Pci(0x2,0x0) is given as 02010000 for setups with dGPU. In the example immediately below, the device-id given for an example system with dGPU output is 26010000. One value should be corrected to the other. I uploaded to the slowgeek "sanity checker" but it does not appear that that page checks these DeviceProperties.

https://dortania.github.io/OpenCore-Install-Guide/config.plist/sandy-bridge.html#deviceproperties

**Comment by donderstock** [comment]
There is a more minor error in the same section for PciRoot(0x0)/Pci(0x16,0x0): "This is not needed if you have a 7 series motherboard(ie. H61, B65, Q65, P67, H67, Q67, Z68)."

**Comment by khronokernel** [comment]
Don't follow images closely, as mentioned in the guide:
> Do note that images will not always be the most up-to-date so please read the text below them

Will fix the image eventually, however currently busy with other work unfortunately.
> There is a more minor error in the same section for PciRoot(0x0)/Pci(0x16,0x0): "This is not needed if you have a 7 series motherboard(ie. H61, B65, Q65, P67, H67, Q67, Z68)."

Resolved

**Comment by 5T33Z0** [comment]
The configuration error the o.p. reported is still present in the guide for 2,5 years now:

![Bildschirmfoto 2023-05-24 um 17 18 43](https://github.com/dortania/bugtracker/assets/76865553/c31a4914-f136-4847-ab15-c4e3f247a224)
